Source/PromotionCMS/PromotionCMS/Areas/Admin/Controllers/UsersManagerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PromotionCMS.Areas.Admin.Models;

namespace PromotionCMS.Areas.Admin.Controllers
{
    public class UsersManagerController : BaseController
    {
        //thangnh 25/02/2018
        // GET: /Admin/UsersManager/
        [HasCredential(FunctionName = "VIEW_USER")]
        public ActionResult Index()
        {
            var roles = (from r in Dbcontext.CMS_ROLES select r);
            var rspList = roles.ToList();
            Dbcontext.PROC_CMS_USER_LOG_INSERT(CurrentUser.UserName, "USERMANAGER", "", "", MyIp(), "Tìm Kiếm", DateTime.Now);
            return View(rspList);
        }
        [Route("user/get-user-list")]
        [HasCredential(FunctionName = "VIEW_USER")]
        public JsonResult Search(string userName, string status, int roleId, int pageNo, string tableListLength)
        {
            if (string.IsNullOrEmpty(userName))
            {
                userName = null;
            }
            if (string.IsNullOrEmpty(status))
            {
                status = null;
            }

            roleId = roleId == 0 ? -1 : roleId;
            var listLength = String.IsNullOrEmpty(tableListLength) ? 10 : int.Parse(tableListLength);

            try
            {
                var totalRow = new ObjectParameter("P_TOTALROW", typeof(int));
                var model = Dbcontext.PROC_CMS_USERS_SEARCH(listLength, pageNo, totalRow, userName, status, roleId);
                var rspList = model.ToList();
                return Json(
                    new
                    {
                        Success = true,
                        TotalRow = totalRow.Value,
                        RspList = rspList
                    });
            }
            catch (Exception ex)
            {
                Log.ErrorFormat("Error: {0}, stack: {1}", ex.Message, ex.StackTrace);
                return Json(
                    new
                    {
                        Success = false
                    });
            }
        }

        //
        // GET: /Admin/UsersManager/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Admin/UsersManager/Create
        [HttpPost]
        public ActionResult ChekUserName(string userName)
        {
            try
            {
                if (!string.IsNullOrEmpty(userName))
                {
                    var success1 = false;
                    var checkid = (from u in Dbcontext.CMS_USERS where (u.USERNAME == userName) select u)
                        .FirstOrDefault();
                    if (checkid == null)
                        success1 = true;
                    return Json(new { success = success1, responseText = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                Log.ErrorFormat("Error: {0}, stack: {1}", ex.Message, ex.StackTrace);
                return RedirectToAction("Create");
            }
        }
        [HasCredential(FunctionName = "ADD_USER")]
        public ActionResult Create()
        {
            var roles = (from r in Dbcontext.CMS_ROLES select r);
            var rspList = roles.ToList();
            return View(rspList);
        }

        //
        // POST: /Admin/UsersManager/Create
        [HttpPost]
        [HasCredential(FunctionName = "ADD_USER")]
        public ActionResult Create(FormCollection collection, UsersManagerModel model)
        {
            try
            {
                var checkid = (from u in Dbcontext.CMS_USERS where (u.USERNAME == model.Username) select u)
                    .FirstOrDefault();
                if (checkid == null)
                {
                    var encryPassword = FormsAuthentication.HashPasswordForStoringInConfigFile(model.Password, "md5");
                    var rs = Dbcontext.PROC_CMS_USERS_INSERT(model.Username, model.Email, model.Firstname, model.Lastname, model.Fullname, encryPassword, DateTime.Now, model.RoleId, "1", CurrentUser.UserName);
                    var dataLog = ser.Serialize(model);
                    Dbcontext.PROC_CMS_USER_LOG_INSERT(CurrentUser.UserName, "USERMANAGER", "", dataLog, MyIp(), "Thêm mới", DateTime.Now);
                    if (rs < 1)
                    {
                        TempData["RspCode"] = "99";
                        return RedirectToAction("Create");
                    }
                }
                else
                {
                    TempData["RspCode"] = "99";
                    return RedirectToAction("Create");
                }

            }
            catch (Exception ex)
            {
                Log.ErrorFormat("Error: {0}, stack: {1}", ex.Message, ex.StackTrace);
                TempData["RspCode"] = "99";
                return RedirectToAction("Create");
            }
            TempData["RspCode"] = "00";
            TempData["Message"] = "Thêm mới người dùng thành công";
            return RedirectToAction("Index");
        }

        //
        // GET: /Admin/UsersManager/Edit/5
        [HasCredential(FunctionName = "EDIT_USER")]
        public ActionResult Edit(int id)
        {
            var roles = (from r in Dbcontext.CMS_ROLES select r);
            ViewBag.ListRoles = roles.ToList();
            var user = (from cmsUsers in Dbcontext.CMS_USERS where (cmsUsers.USER_ID == id) select cmsUsers)
                .FirstOrDefault();
            return View(user);
        }

        //
        // POST: /Admin/UsersManager/Edit/5
        [HttpPost]
        [HasCredential(FunctionName = "EDIT_USER")]
        public ActionResult Edit(FormCollection collection,UsersManagerModel model)
        {
            try
            {
                var rs = Dbcontext.PROC_CMS_USERS_UPDATE(model.UserId,model.Email,model.Fullname,DateTime.Now, model.RoleId,CurrentUser.UserName);
                if (rs < 1)
                {
                    TempData["RspCode"] = "99";
                    return RedirectToAction("Edit", new { userId = model.UserId });
                }
            }
            catch (Exception ex)
            {
                Log.ErrorFormat("Error: {0}, stack: {1}", ex.Message, ex.StackTrace);
                TempData["RspCode"] = "99";
                return RedirectToAction("Edit", new { userId = model.UserId });
            }
            TempData["RspCode"] = "00";
            TempData["Message"] = "Cập nhật người dùng thành công";
            var dataLog = ser.Serialize(model);
            Dbcontext.PROC_CMS_USER_LOG_INSERT(CurrentUser.UserName, "USERMANAGER", "", dataLog, MyIp(), "Chỉnh sửa", DateTime.Now);
            return RedirectToAction("Index");
        }

        [Route("user/update-status")]
        [HasCredential(FunctionName = "EDIT_USER")]
        public JsonResult UpdateStatus(int userId, string isLocked)
        {
            try
            {
                var rspCode = "";
                var statusUpdate = isLocked == "1" ? "0" : "1";
                var rs = Dbcontext.PROC_CMS_USERS_STATUS(userId, statusUpdate);
                rspCode = rs < 1 ? "99" : "00";
                var dataLog = ser.Serialize(isLocked);
                Dbcontext.PROC_CMS_USER_LOG_INSERT(CurrentUser.UserName, "USERMANAGER", "", dataLog, MyIp(), "Update Status", DateTime.Now);
                var message = "";
                if (rspCode == "00")
                {
                    message = statusUpdate == "1" ? "Người dùng cập nhật trạng thái hoạt động thành công" : "Cập nhật trạng thái tạm khóa cho người dùng thành công";
                }
                else
                {
                    message = "Đã xảy ra lỗi trong quá trình cập nhật. Vui lòng thực hiện lại sau";
                }
                return Json(
                    new
                    {
                        Success = true,
                        RspCode = rspCode,
                        Message = message
                    });
            }
            catch (Exception ex)
            {
                Log.ErrorFormat("Error: {0}, stack: {1}", ex.Message, ex.StackTrace);
                return Json(
                    new
                    {
                        Success = false
                    });
            }
        }
        [HasCredential(FunctionName = "EDIT_PASS_USER")]
        public ActionResult ChangePass(int id)
        {
            var user = (from cmsUsers in Dbcontext.CMS_USERS where (cmsUsers.USER_ID == id) select cmsUsers)
                .FirstOrDefault();
            return View(user);
        }
        [HttpPost]
        [HasCredential(FunctionName = "EDIT_PASS_USER")]
        public ActionResult ChangePass(FormCollection collection,UsersManagerModel model)
        {
            try
            {
                var encryPassword = FormsAuthentication.HashPasswordForStoringInConfigFile(model.Password, "md5");
                var rs = Dbcontext.PROC_CMS_USERS_UPDATE_PASS(model.UserId, encryPassword);
                if (rs < 1)
                {
                    TempData["RspCode"] = "99";
                    return RedirectToAction("ChangePass", new { userId = model.UserId });
                }
            }
            catch (Exception ex)
            {
                Log.ErrorFormat("Error: {0}, stack: {1}", ex.Message, ex.StackTrace);
                TempData["RspCode"] = "99";
                return RedirectToAction("ChangePass", new { userId = model.UserId });
            }
            TempData["RspCode"] = "00";
            TempData["Message"] = "Cập nhật password thành công";

Source/PromotionCMS/PromotionCMS/Areas/Admin/Views/UsersManager/ChangePass.cshtml
@using PromotionCMS.Areas.Admin.Models
@model PromotionCMS.Models.CMS_USERS
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Resources/plugin/ckfinder/ckfinder.js")" type="text/javascript"></script>
<div class="main-content" ng-controller="CategoryController">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="default-icon fa fa-home home-icon"></i><a href="#">Home</a></li>
            <li>Quản lý người dùng</li>
            <li>Đổi mật khẩu</li>
        </ul>
        <!-- /.breadcrumb -->
        @* <div class="pull-right timer"> Đăng nhập lần cuối vào lúc 04/12/2015 01:42:56 </div>*@
    </div>
    <div class="page-content">
        <div class="page-content-area">
            <div class="page-header">
                <h1>Thay đổi mật khẩu</h1>
            </div>
            <div class="row">
                @if (ReferenceEquals(TempData["RspCode"], "99"))
                {
                    <div class="col-md-12">
                        <span class="error">Kết nối bị gián đoạn. Vui lòng thử lại</span>
                    </div>

                }
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" id="form" role="form" action="@Url.Action("ChangePass")" method="POST">
                        <input type="hidden" id="UserId" name="UserId" value="@Model.USER_ID">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Mật Khẩu mới<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <input type="password" id="Password" name="Password" maxlength="50" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Nhập lại mật khẩu mới<font style="color: red">(*)</font></label>
                            <div class="col-sm-9">
                                <input type="password" id="ConfirmPassword" name="ConfirmPassword" maxlength="50" class="form-control">
                                <span id='message'></span>
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <a href="@Url.Action("Index", "UsersManager")" class="btn btn-default">Quay lại</a>
                                <button type="submit" id="submit" class="btn btn-primary">Lưu lại</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.page-content-area -->
    </div>
    <!-- /.page-content -->
</div>
<!-- /.main-content -->
@section scripts{
    <script type="text/javascript">
        $('#ConfirmPassword').on('keyup', function () {
            if ($('#Password').val() != $('#ConfirmPassword').val()) {
                $('#message').html('Thông tin mật khẩu nhập lại chưa chính xác').css('color', 'red');
                document.getElementById('submit').disabled = true;
            } else {
                $('#message').html('');
                document.getElementById('submit').disabled = false;
            }
        });
        $(document).ready(function () {
            $('#form').validate({
                rules: {
                   
                    Password: {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    ConfirmPassword: {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    }
                },
                messages: {
                   
                    Password: {
                        required: "Mật khẩu bắt buộc nhập",
                        minlength: "Mật khẩu có độ dài từ 1 – 50 ký tự",
                        maxlength: "Mật khẩu có độ dài từ 1 – 50 ký tự"
                    },
                    ConfirmPassword: {
                        required: "Nhập lại mật khẩu bắt buộc nhập",
                        minlength: "Nhập lại mật khẩu có độ dài từ 1 – 50 ký tự",
                        maxlength: "Nhập lại mật khẩu có độ dài từ 1 – 50 ký tự"
                    }
                }
            });
        });
    </script>
}

Source/PromotionCMS/PromotionCMS/Areas/Admin/Views/UsersManager/Create.cshtml
@using PromotionCMS.Areas.Admin.Models
@model List<PromotionCMS.Models.CMS_ROLES>
@{
    ViewBag.Title = "Cập nhật người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Resources/plugin/ckfinder/ckfinder.js")" type="text/javascript"></script>
<div class="main-content" ng-controller="CategoryController">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="default-icon fa fa-home home-icon"></i><a href="#">Home</a></li>
            <li>Quản lý người dùng</li>
            <li>Cập nhật tài khoản người dùng(Thêm mới)</li>
        </ul>
        <!-- /.breadcrumb -->
        @* <div class="pull-right timer"> Đăng nhập lần cuối vào lúc 04/12/2015 01:42:56 </div>*@
    </div>
    <div class="page-content">
        <div class="page-content-area">
            <div class="page-header">
                <h1>Cập nhật tài khoản người dùng</h1>
            </div>
            <div class="row">
                @if (ReferenceEquals(TempData["RspCode"], "99"))
                {
                    <div class="col-md-12">
                        <span class="error">Kết nối bị gián đoạn. Vui lòng thử lại</span>
                    </div>

                }
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" id="form" role="form" action="@Url.Action("Create")" method="POST">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top">Tên đăng nhập<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <input type="text" id="Username" name="Username" maxlength="200" class="form-control">
                                <span id='checkusername'></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Họ tên<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <input type="text" id="Fullname" name="Fullname" maxlength="200" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Email </label>
                            <div class="col-sm-9">
                                <input type="text" id="Email" name="Email" maxlength="100" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Mật Khẩu<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <input type="password" id="Password" name="Password" maxlength="50" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Nhập lại mật khẩu<font style="color: red">(*)</font></label>
                            <div class="col-sm-9">
                                <input type="password" id="ConfirmPassword" name="ConfirmPassword" maxlength="50" class="form-control">
                                <span id='message'></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="form-field-1">Nhóm quyền<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <select class="form-control" name="RoleId" id="RoleId">
                                    @{
                                        foreach (var item in Model)
                                        {
                                            <option value="@item.ROLE_ID">@item.ROLE_NAME</option>
                                        }
                                    }
                                </select>

                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <a href="@Url.Action("Index","UsersManager")" class="btn btn-default">Quay lại</a>
                                <button type="submit" id="submit" class="btn btn-primary">Lưu lại</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.page-content-area -->
    </div>
    <!-- /.page-content -->
</div>
<!-- /.main-content -->
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var val = '';
            $("#Username").change(function () {
                val = $("#Username").val();
                if (val !== '') {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("ChekUserName")',
                        dataType: "json",
                        data: { userName: val },
                        success: function (states) {
                            if (!states.success) {
                                $('#checkusername').html('Người dùng đã tồn tại').css('color', 'red');
                                document.getElementById('submit').disabled = true;
                            } else {
                                $('#checkusername').html('');
                                document.getElementById('submit').disabled = false;
                            }
                        },
                        error: function (ex) {
                            alert("Failed to retrieve states." + ex);
                        }
                    });
                }
                return false;
            });
        });
        $('#ConfirmPassword').on('keyup', function () {
            if ($('#Password').val() != $('#ConfirmPassword').val()) {
                $('#message').html('Thông tin mật khẩu nhập lại chưa chính xác').css('color', 'red');
                document.getElementById('submit').disabled = true;
            } else {
                $('#message').html('');
                document.getElementById('submit').disabled = false;
            }
        });
        $(document).ready(function () {
            $('#form').validate({
                rules: {
                    Username: {
                        required: true,
                        minlength: 1,
                        maxlength: 200
                    },
                    Fullname: {
                        required: true,
                        minlength: 1,
                        maxlength: 200
                    },
                    Email: {
                        minlength: 1,
                        maxlength: 100,
                        email: true
                    },
                    Password: {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    ConfirmPassword: {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    RoleId: {
                        required: true
                    }

                },
                messages: {
                    Username: {
                        required: "Tên đăng nhập bắt buộc nhập",
                        minlength: "Tên đăng nhập có độ dài từ 1 – 200 ký tự",
                        maxlength: "Tên đăng nhập có độ dài từ 1 – 200 ký tự"
                    },
                    Fullname: {
                        required: "Họ tên bắt buộc nhập",
                        minlength: "Họ tên có độ dài từ 1 – 200 ký tự",
                        maxlength: "Họ tên có độ dài từ 1 – 200 ký tự"
                    },
                    Email: {
                        minlength: "Thông tin Email có độ dài từ 1 – 100 ký tự",
                        maxlength: "Thông tin Email có độ dài từ 1 – 100 ký tự",
                        email: "Định dạng mail không đúng"
                    },
                    Password: {
                        required: "Mật khẩu bắt buộc nhập",
                        minlength: "Mật khẩu có độ dài từ 1 – 50 ký tự",
                        maxlength: "Mật khẩu có độ dài từ 1 – 50 ký tự"
                    },
                    ConfirmPassword: {
                        required: "Nhập lại mật khẩu bắt buộc nhập",
                        minlength: "Nhập lại mật khẩu có độ dài từ 1 – 50 ký tự",
                        maxlength: "Nhập lại mật khẩu có độ dài từ 1 – 50 ký tự"
                    },
                    RoleId: {
                        required: "Nhóm quyền chưa được lựa chọn"
                    }
                }
            });
        });
    </script>
}

Source/PromotionCMS/PromotionCMS/Areas/Admin/Views/UsersManager/Edit.cshtml
@using PromotionCMS.Areas.Admin.Models
@using PromotionCMS.Models
@model PromotionCMS.Models.CMS_USERS
@{
    ViewBag.Title = "Cập nhật người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var listRoles = (List<CMS_ROLES>)ViewBag.ListRoles;
}
<script src="@Url.Content("~/Resources/plugin/ckfinder/ckfinder.js")" type="text/javascript"></script>
<div class="main-content" ng-controller="CategoryController">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="default-icon fa fa-home home-icon"></i><a href="#">Home</a></li>
            <li>Quản lý người dùng</li>
            <li>Cập nhật tài khoản người dùng(Sửa)</li>
        </ul>
        <!-- /.breadcrumb -->
        @* <div class="pull-right timer"> Đăng nhập lần cuối vào lúc 04/12/2015 01:42:56 </div>*@
    </div>
    <div class="page-content">
        <div class="page-content-area">
            <div class="page-header">
                <h1>Cập nhật tài khoản người dùng</h1>
            </div>
            <div class="row">
                @if (ReferenceEquals(TempData["RspCode"], "99"))
                {
                    <div class="col-md-12">
                        <span class="error">Kết nối bị gián đoạn. Vui lòng thử lại</span>
                    </div>

                }
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" id="form" role="form" action="@Url.Action("Edit")" method="POST">
                        <input type="hidden" id="UserId" name="UserId" value="@Model.USER_ID">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top">Tên đăng nhập<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                @Model.USERNAME
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Họ tên<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <input type="text" id="Fullname" name="Fullname" value="@Model.FULLNAME" maxlength="200" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right p_top" for="form-field-1">Email</label>
                            <div class="col-sm-9">
                                <input type="text" id="Email" name="Email" maxlength="100" value="@Model.EMAIL" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="form-field-1">Nhóm quyền<font style="color: red">(*)</font> </label>
                            <div class="col-sm-9">
                                <select class="form-control" name="RoleId" id="RoleId" >
                                    @foreach (var item in listRoles)
                                    {
                                        if (item.ROLE_ID == Model.ROLE_ID)
                                        {
                                            <option selected="selected" value="@item.ROLE_ID">@item.ROLE_NAME</option>
                                        }
                                        else
                                        {
                                            <option value="@item.ROLE_ID">@item.ROLE_NAME</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <a href="@Url.Action("Index", "UsersManager")" class="btn btn-default">Quay lại</a>
                                <button type="submit" id="submit" class="btn btn-primary">Lưu lại</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.page-content-area -->
    </div>
    <!-- /.page-content -->
</div>
<!-- /.main-content -->
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $('#form').validate({
                rules: {
                    Username: {
                        required: true,
                        minlength: 1,
                        maxlength: 200
                    },
                    Fullname: {
                        required: true,
                        minlength: 1,
                        maxlength: 200
                    },
                    Email: {
                        minlength: 1,
                        maxlength: 100,
                        email: true
                    },
                    RoleId: {
                        required: true
                    }

                },
                messages: {
                    Username: {
                        required: "Tên đăng nhập bắt buộc nhập",
                        minlength: "Tên đăng nhập có độ dài từ 1 – 200 ký tự",
                        maxlength: "Tên đăng nhập có độ dài từ 1 – 200 ký tự"
                    },
                    Fullname: {
                        required: "Họ tên bắt buộc nhập",
                        minlength: "Họ tên có độ dài từ 1 – 200 ký tự",
                        maxlength: "Họ tên có độ dài từ 1 – 200 ký tự"
                    },
                    Email: {
                        minlength: "Thông tin Email có độ dài từ 1 – 100 ký tự",
                        maxlength: "Thông tin Email có độ dài từ 1 – 100 ký tự",
                        email: "Định dạng mail không đúng"
                    },
                    RoleId: {
                        required: "Nhóm quyền chưa được lựa chọn"
                    }
                }
            });
        });
    </script>
}